// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dtw_lanes_cpp
NumericVector dtw_lanes_cpp(NumericMatrix P, NumericVector q, std::string precision);
RcppExport SEXP _dtwsom_dtw_lanes_cpp(SEXP PSEXP, SEXP qSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type P(PSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< std::string >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(dtw_lanes_cpp(P, q, precision));
    return rcpp_result_gen;
END_RCPP
}
// dtw_scalar_cpp
NumericVector dtw_scalar_cpp(NumericMatrix P, NumericVector q);
RcppExport SEXP _dtwsom_dtw_scalar_cpp(SEXP PSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type P(PSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(dtw_scalar_cpp(P, q));
    return rcpp_result_gen;
END_RCPP
}
// dtwsom_train_cpp
List dtwsom_train_cpp(List data, List codes, NumericMatrix udist, List params, std::string precision);
RcppExport SEXP _dtwsom_dtwsom_train_cpp(SEXP dataSEXP, SEXP codesSEXP, SEXP udistSEXP, SEXP paramsSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< List >::type codes(codesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type udist(udistSEXP);
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< std::string >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(dtwsom_train_cpp(data, codes, udist, params, precision));
    return rcpp_result_gen;
END_RCPP
}
// dtwsom_map_cpp
List dtwsom_map_cpp(List codes, List data, int window, double max_step, int max_length_diff, int threads, std::string precision);
RcppExport SEXP _dtwsom_dtwsom_map_cpp(SEXP codesSEXP, SEXP dataSEXP, SEXP windowSEXP, SEXP max_stepSEXP, SEXP max_length_diffSEXP, SEXP threadsSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type codes(codesSEXP);
    Rcpp::traits::input_parameter< List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type max_step(max_stepSEXP);
    Rcpp::traits::input_parameter< int >::type max_length_diff(max_length_diffSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< std::string >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(dtwsom_map_cpp(codes, data, window, max_step, max_length_diff, threads, precision));
    return rcpp_result_gen;
END_RCPP
}
// dtw_cross_cpp
NumericMatrix dtw_cross_cpp(List a, List b, int window, double max_step, int threads, std::string precision);
RcppExport SEXP _dtwsom_dtw_cross_cpp(SEXP aSEXP, SEXP bSEXP, SEXP windowSEXP, SEXP max_stepSEXP, SEXP threadsSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type a(aSEXP);
    Rcpp::traits::input_parameter< List >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type max_step(max_stepSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< std::string >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(dtw_cross_cpp(a, b, window, max_step, threads, precision));
    return rcpp_result_gen;
END_RCPP
}
// dtw_pairwise_cpp
NumericMatrix dtw_pairwise_cpp(List a, int window, double max_step, int threads, std::string precision);
RcppExport SEXP _dtwsom_dtw_pairwise_cpp(SEXP aSEXP, SEXP windowSEXP, SEXP max_stepSEXP, SEXP threadsSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type max_step(max_stepSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< std::string >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(dtw_pairwise_cpp(a, window, max_step, threads, precision));
    return rcpp_result_gen;
END_RCPP
}
// dtw_distance_cpp
List dtw_distance_cpp(NumericMatrix a, NumericMatrix b, int window, double max_step, std::string precision);
RcppExport SEXP _dtwsom_dtw_distance_cpp(SEXP aSEXP, SEXP bSEXP, SEXP windowSEXP, SEXP max_stepSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type max_step(max_stepSEXP);
    Rcpp::traits::input_parameter< std::string >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(dtw_distance_cpp(a, b, window, max_step, precision));
    return rcpp_result_gen;
END_RCPP
}
// dtw_warp_cpp
NumericMatrix dtw_warp_cpp(NumericMatrix w, NumericMatrix x, int window, double max_step);
RcppExport SEXP _dtwsom_dtw_warp_cpp(SEXP wSEXP, SEXP xSEXP, SEXP windowSEXP, SEXP max_stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type max_step(max_stepSEXP);
    rcpp_result_gen = Rcpp::wrap(dtw_warp_cpp(w, x, window, max_step));
    return rcpp_result_gen;
END_RCPP
}
// dtwsom_threads_cpp
int dtwsom_threads_cpp();
RcppExport SEXP _dtwsom_dtwsom_threads_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(dtwsom_threads_cpp());
    return rcpp_result_gen;
END_RCPP
}
// dtwsom_precisions_cpp
CharacterVector dtwsom_precisions_cpp();
RcppExport SEXP _dtwsom_dtwsom_precisions_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(dtwsom_precisions_cpp());
    return rcpp_result_gen;
END_RCPP
}
// dtwsom_build_info_cpp
List dtwsom_build_info_cpp();
RcppExport SEXP _dtwsom_dtwsom_build_info_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(dtwsom_build_info_cpp());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dtwsom_dtw_lanes_cpp", (DL_FUNC) (RCPP_FUNC) &_dtwsom_dtw_lanes_cpp, 3},
    {"_dtwsom_dtw_scalar_cpp", (DL_FUNC) (RCPP_FUNC) &_dtwsom_dtw_scalar_cpp, 2},
    {"_dtwsom_dtwsom_train_cpp", (DL_FUNC) (RCPP_FUNC) &_dtwsom_dtwsom_train_cpp, 5},
    {"_dtwsom_dtwsom_map_cpp", (DL_FUNC) (RCPP_FUNC) &_dtwsom_dtwsom_map_cpp, 7},
    {"_dtwsom_dtw_cross_cpp", (DL_FUNC) (RCPP_FUNC) &_dtwsom_dtw_cross_cpp, 6},
    {"_dtwsom_dtw_pairwise_cpp", (DL_FUNC) (RCPP_FUNC) &_dtwsom_dtw_pairwise_cpp, 5},
    {"_dtwsom_dtw_distance_cpp", (DL_FUNC) (RCPP_FUNC) &_dtwsom_dtw_distance_cpp, 5},
    {"_dtwsom_dtw_warp_cpp", (DL_FUNC) (RCPP_FUNC) &_dtwsom_dtw_warp_cpp, 4},
    {"_dtwsom_dtwsom_threads_cpp", (DL_FUNC) (RCPP_FUNC) &_dtwsom_dtwsom_threads_cpp, 0},
    {"_dtwsom_dtwsom_precisions_cpp", (DL_FUNC) (RCPP_FUNC) &_dtwsom_dtwsom_precisions_cpp, 0},
    {"_dtwsom_dtwsom_build_info_cpp", (DL_FUNC) (RCPP_FUNC) &_dtwsom_dtwsom_build_info_cpp, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_dtwsom(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
