# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dtw_lanes_cpp <- function(P, q, precision = "double") {
    .Call(`_dtwsom_dtw_lanes_cpp`, P, q, precision)
}

dtw_scalar_cpp <- function(P, q) {
    .Call(`_dtwsom_dtw_scalar_cpp`, P, q)
}

dtwsom_train_cpp <- function(data, codes, udist, params, precision = "double") {
    .Call(`_dtwsom_dtwsom_train_cpp`, data, codes, udist, params, precision)
}

dtwsom_map_cpp <- function(codes, data, window, max_step, max_length_diff, threads, precision = "double") {
    .Call(`_dtwsom_dtwsom_map_cpp`, codes, data, window, max_step, max_length_diff, threads, precision)
}

dtw_cross_cpp <- function(a, b, window, max_step, threads, precision = "double") {
    .Call(`_dtwsom_dtw_cross_cpp`, a, b, window, max_step, threads, precision)
}

dtw_pairwise_cpp <- function(a, window, max_step, threads, precision = "double") {
    .Call(`_dtwsom_dtw_pairwise_cpp`, a, window, max_step, threads, precision)
}

dtw_distance_cpp <- function(a, b, window, max_step, precision = "double") {
    .Call(`_dtwsom_dtw_distance_cpp`, a, b, window, max_step, precision)
}

dtw_warp_cpp <- function(w, x, window, max_step) {
    .Call(`_dtwsom_dtw_warp_cpp`, w, x, window, max_step)
}

dtwsom_threads_cpp <- function() {
    .Call(`_dtwsom_dtwsom_threads_cpp`)
}

dtwsom_precisions_cpp <- function() {
    .Call(`_dtwsom_dtwsom_precisions_cpp`)
}

dtwsom_build_info_cpp <- function() {
    .Call(`_dtwsom_dtwsom_build_info_cpp`)
}

